'use client'

import { useMemo, useState } from 'react'
import Image from 'next/image'
import { appointments, billing, formatRole, getInitials, metrics, navItems, pageTitle, patients, reports, roleLabels, storeUser, type NiaRole, type NiaUser } from '../lib/nia/data'

export function LoginScreen({ onLogin }: { onLogin: (user: NiaUser) => void }) {
  const [selectedRole, setSelectedRole] = useState<NiaRole>('owner')
  const selected = ['owner', 'admin', 'dentist', 'assistant', 'front_office', 'claims'] as NiaRole[]
  const users = selected.map((role) => ({ role, label: roleLabels[role] }))
  return <main className="login-screen"><section className="login-card">
    <div className="login-logo"><Image src="/nia/nia-logo.png" alt="NiaCARE logo" width={54} height={54} /><div><strong>NiaCARE</strong><span>Dental operations, connected.</span></div></div>
    <div className="login-copy"><p className="eyebrow">SECURE FACILITY ACCESS</p><h1>Welcome back.</h1><p>Choose your role to enter the NiaCARE workspace.</p></div>
    <div className="role-list">{users.map(({ role, label }) => <button key={role} className={`role-option ${selectedRole === role ? 'selected' : ''}`} onClick={() => setSelectedRole(role)}><span className="role-avatar">{roleLabels[role].slice(0, 2)}</span><span>{label}</span><span className="role-check">{selectedRole === role ? '✓' : '→'}</span></button>)}</div>
    <button className="primary-button login-button" onClick={() => { const user = (selected as NiaRole[]).map((r) => ({ id: `u_${r === 'owner' ? 'owner_neema' : r === 'admin' ? 'admin_yusuf' : r === 'dentist' ? 'dr_amani' : r === 'assistant' ? 'asst_fatma' : r === 'front_office' ? 'fo_brenda' : 'claims_zainab'}`, name: roleLabels[r], role: r, initials: roleLabels[r].slice(0,2) } as NiaUser)).find((u) => u.role === selectedRole)!; storeUser(user.id); onLogin(user) }}>Continue as {roleLabels[selectedRole]}</button>
    <p className="login-footnote">NiaCARE facility operations system · v2.4</p>
  </section></main>
}

export function Sidebar({ activePage, user, onNavigate, onLogout }: { activePage: string; user: NiaUser; onNavigate: (page: string) => void; onLogout: () => void }) {
  return <aside className="sidebar"><div className="sidebar-brand"><Image src="/nia/nia-logo.png" alt="NiaCARE logo" width={40} height={40} /><div><strong>NiaCARE</strong><span>FACILITY CONSOLE</span></div></div><div className="facility-switcher"><span className="facility-mark">NC</span><span><b>Nia Dental Centre</b><small>Westlands, Nairobi</small></span><span>⌄</span></div><nav className="sidebar-nav"><p className="nav-label">WORKSPACE</p>{navItems.map((item) => <button key={item.id} className={activePage === item.id ? 'active' : ''} onClick={() => onNavigate(item.id)}><span className="nav-icon">{item.icon}</span>{item.label}</button>)}<p className="nav-label secondary-label">FINANCE</p><button className={activePage === 'billing' ? 'active' : ''} onClick={() => onNavigate('billing')}><span className="nav-icon">◈</span>Billing</button></nav><div className="sidebar-bottom"><div className="user-row"><span className="user-avatar">{user.initials}</span><span><b>{user.name}</b><small>{formatRole(user.role)}</small></span><button className="icon-button" onClick={onLogout} aria-label="Log out">↪</button></div></div></aside>
}

export function Topbar({ user, activePage, onMenu }: { user: NiaUser; activePage: string; onMenu: () => void }) { return <header className="topbar"><button className="mobile-menu" onClick={onMenu}>☰</button><div><p className="breadcrumb">NIA DENTAL CENTRE <span>/</span> WORKSPACE</p><h2>{pageTitle(activePage)}</h2></div><div className="topbar-actions"><button className="topbar-icon" aria-label="Search">⌕</button><button className="topbar-icon" aria-label="Notifications">♧<i /></button><div className="topbar-user"><span>{user.initials}</span><b>{user.name}</b><small>{formatRole(user.role)}</small></div></div></header> }

function StatusBadge({ children, tone = 'success' }: { children: React.ReactNode; tone?: string }) { return <span className={`status-badge ${tone}`}>{children}</span> }

export function DashboardPage({ onNavigate }: { onNavigate: (page: string) => void }) { return <div className="page-content"><div className="page-heading"><div><p className="eyebrow">THURSDAY, AUGUST 14, 2026</p><h1>Good morning, Neema.</h1><p className="muted">Here is what is happening across your facility today.</p></div><button className="primary-button" onClick={() => onNavigate('appointments')}>+ New appointment</button></div><div className="metric-grid">{metrics.map((metric) => <div className="metric-card" key={metric.label}><div className="metric-icon">{metric.icon}</div><div><p>{metric.label}</p><strong>{metric.value}</strong><small className={metric.change.startsWith('-') ? 'negative' : ''}>{metric.change} <span>vs last month</span></small></div></div>)}</div><div className="dashboard-grid"><section className="panel appointment-panel"><div className="panel-header"><div><p className="eyebrow">TODAY</p><h3>Upcoming appointments</h3></div><button className="text-button" onClick={() => onNavigate('appointments')}>View calendar →</button></div><div className="appointment-list">{appointments.map((item) => <div className="appointment-row" key={`${item.time}-${item.patient}`}><time>{item.time}</time><span className="appointment-dot" /><div className="appointment-details"><b>{item.patient}</b><span>{item.procedure} · {item.dentist}</span></div><StatusBadge tone={item.status === 'Waiting' ? 'warning' : 'success'}>{item.status}</StatusBadge></div>)}</div></section><section className="panel activity-panel"><div className="panel-header"><div><p className="eyebrow">FACILITY PULSE</p><h3>At a glance</h3></div><button className="text-button" onClick={() => onNavigate('reports')}>Reports →</button></div><div className="pulse-chart"><div className="chart-bars">{[52, 68, 44, 78, 62, 86, 72, 92, 66, 80, 74, 98].map((height, index) => <span key={index} style={{ height: `${height}%` }} />)}</div><div className="chart-labels"><span>Mar</span><span>Apr</span><span>May</span><span>Jun</span><span>Jul</span><span>Aug</span></div></div><div className="pulse-footer"><span><i className="legend-dot purple" />Appointments</span><strong>+18.9%</strong></div></section></div></div> }

export function PatientsPage({ onOpen }: { onOpen: (id: string) => void }) { const [query, setQuery] = useState(''); const filtered = useMemo(() => patients.filter((patient) => patient.name.toLowerCase().includes(query.toLowerCase()) || patient.id.toLowerCase().includes(query.toLowerCase())), [query]); return <div className="page-content"><div className="page-heading"><div><p className="eyebrow">PATIENT DIRECTORY</p><h1>Patients</h1><p className="muted">Manage patient records and treatment journeys.</p></div><button className="primary-button">+ Add patient</button></div><section className="panel table-panel"><div className="table-toolbar"><div className="search-field"><span>⌕</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search patients or ID..." /></div><button className="filter-button">Filter <span>≡</span></button></div><div className="table-wrap"><table><thead><tr><th>Patient</th><th>Contact</th><th>Status</th><th>Last visit</th><th>Next visit</th><th /></tr></thead><tbody>{filtered.map((patient) => <tr key={patient.id} onClick={() => onOpen(patient.id)}><td><div className="patient-cell"><span className="patient-avatar">{getInitials(patient.name)}</span><span><b>{patient.name}</b><small>{patient.id} · {patient.age} years</small></span></div></td><td>{patient.phone}</td><td><StatusBadge>{patient.status}</StatusBadge></td><td>{patient.lastVisit}</td><td>{patient.nextVisit}</td><td><button className="row-action" onClick={(event) => { event.stopPropagation(); onOpen(patient.id) }}>→</button></td></tr>)}</tbody></table></div></section></div> }

export function AppointmentsPage() { return <div className="page-content"><div className="page-heading"><div><p className="eyebrow">SCHEDULE</p><h1>Appointments</h1><p className="muted">Coordinate today&apos;s chair time across the facility.</p></div><button className="primary-button">+ New appointment</button></div><section className="panel calendar-panel"><div className="calendar-header"><button className="icon-button">‹</button><div><b>August 2026</b><span>Week 33</span></div><button className="icon-button">›</button><button className="filter-button today-button">Today</button></div><div className="week-grid">{['MON 10','TUE 11','WED 12','THU 13','FRI 14','SAT 15'].map((day, index) => <div className={index === 4 ? 'day-column current' : 'day-column'} key={day}><b>{day}</b><span className="day-number">{10 + index}</span>{index === 4 && <><div className="calendar-event event-purple"><b>08:30</b><span>Amara Mwangi</span></div><div className="calendar-event event-gold"><b>11:00</b><span>Lilian Njeri</span></div><div className="calendar-event event-blue"><b>14:00</b><span>David Kiptoo</span></div></>}</div>)}</div></section></div> }

export function ReportsPage() { return <div className="page-content"><div className="page-heading"><div><p className="eyebrow">INSIGHTS</p><h1>Reports</h1><p className="muted">A clear view of your facility&apos;s performance.</p></div><button className="filter-button">Aug 2026 ˅</button></div><div className="report-grid">{reports.map((report) => <div className="report-card" key={report.label}><span>{report.label}</span><strong>{report.value}</strong><small>{report.detail}</small><div className={`report-line ${report.tone}`} /></div>)}</div><section className="panel report-panel"><div className="panel-header"><div><p className="eyebrow">REVENUE OVERVIEW</p><h3>Monthly performance</h3></div><StatusBadge tone="success">On track</StatusBadge></div><div className="large-chart">{[28,42,36,58,52,66,61,74,68,81,76,92].map((height, index) => <span key={index} style={{ height: `${height}%` }} />)}</div></section></div> }

export function BillingPage() { return <div className="page-content"><div className="page-heading"><div><p className="eyebrow">FINANCE</p><h1>Billing</h1><p className="muted">Invoices, collections, and facility revenue.</p></div><button className="primary-button">+ Create invoice</button></div><div className="metric-grid billing-metrics"><div className="metric-card"><div className="metric-icon">◈</div><div><p>Outstanding</p><strong>KES 126K</strong><small>18 invoices</small></div></div><div className="metric-card"><div className="metric-icon">✓</div><div><p>Collected this month</p><strong>KES 842K</strong><small className="positive">+18.9% vs July</small></div></div></div><section className="panel table-panel"><div className="panel-header"><div><p className="eyebrow">RECENT ACTIVITY</p><h3>Invoices</h3></div><button className="text-button">Export →</button></div><div className="table-wrap"><table><thead><tr><th>Invoice</th><th>Patient</th><th>Amount</th><th>Status</th><th>Date</th></tr></thead><tbody>{billing.map((item) => <tr key={item.invoice}><td><b>{item.invoice}</b></td><td>{item.patient}</td><td>{item.amount}</td><td><StatusBadge tone={item.status === 'Paid' ? 'success' : 'warning'}>{item.status}</StatusBadge></td><td>{item.date}</td></tr>)}</tbody></table></div></section></div> }

export function SimplePage({ page }: { page: string }) { const labels: Record<string, string> = { 'treatment-plans': 'Treatment Plans', 'follow-ups': 'Follow-ups', team: 'Team & Roles', 'facility-settings': 'Facility Settings' }; return <div className="page-content"><div className="page-heading"><div><p className="eyebrow">NiaCARE WORKSPACE</p><h1>{labels[page] ?? 'Workspace'}</h1><p className="muted">Keep your facility operations organized and moving forward.</p></div><button className="primary-button">+ Create new</button></div><section className="panel empty-panel"><div className="empty-icon">✦</div><h3>{labels[page] ?? 'Workspace'} is ready</h3><p>Your role-based workspace will appear here as records are added.</p><button className="text-button">Explore workspace →</button></section></div> }

export function PatientProfile({ patientId, onBack }: { patientId: string; onBack: () => void }) { const patient = patients.find((item) => item.id === patientId) ?? patients[0]; return <div className="page-content"><button className="back-link" onClick={onBack}>← Back to patients</button><div className="profile-hero"><span className="profile-avatar">{getInitials(patient.name)}</span><div><p className="eyebrow">PATIENT PROFILE · {patient.id}</p><h1>{patient.name}</h1><p className="muted">{patient.age} years · {patient.phone}</p></div><StatusBadge>{patient.status}</StatusBadge></div><div className="profile-grid"><section className="panel"><div className="panel-header"><div><p className="eyebrow">CARE JOURNEY</p><h3>Recent activity</h3></div><button className="text-button">Add note</button></div><div className="timeline"><div><b>Routine review completed</b><span>Aug 08, 2026 · Dr. Amani</span></div><div><b>Treatment plan updated</b><span>Jul 22, 2026 · Front office</span></div><div><b>Patient registered</b><span>Jun 14, 2026 · Nia Dental Centre</span></div></div></section><section className="panel"><p className="eyebrow">NEXT APPOINTMENT</p><h3>{patient.nextVisit}</h3><p className="muted">Follow-up review · 45 minutes</p><button className="primary-button full-button">Manage appointment</button></section></div></div> }
